<?php

namespace App\Console\Commands;

use App\Models\Invoice;
use App\Models\InvoiceItem;
use App\Models\RecurringInvoice;
use Illuminate\Console\Command;
use Illuminate\Support\Str;

class GenerateRecurringInvoices extends Command
{
    protected $signature = 'app:generate-recurring-invoices';
    protected $description = 'Generate invoices from active recurring setups';

    public function handle(): void
    {
        $today = now()->toDateString();
        $recurringInvoices = RecurringInvoice::with('items')
            ->where('status', 'active')
            ->where('next_generation_date', '<=', $today)
            ->get();

        $this->info("Found " . $recurringInvoices->count() . " recurring invoices to process.");

        foreach ($recurringInvoices as $rec) {
            // Generate standard invoice
            $invoiceNumber = 'INV-REC-' . strtoupper(Str::random(6)) . '-' . now()->format('Ymd');
            
            $invoice = Invoice::create([
                'user_id' => $rec->user_id,
                'client_id' => $rec->client_id,
                'invoice_number' => $invoiceNumber,
                'status' => 'sent', // Autogenerated is marked sent
                'subtotal' => $rec->subtotal,
                'tax_rate' => $rec->tax_rate,
                'tax_amount' => $rec->tax_amount,
                'total' => $rec->total,
                'currency' => $rec->currency,
                'notes' => $rec->notes . "\n(Automatically generated from retainer schedule)",
                'issue_date' => $rec->next_generation_date,
                'due_date' => $rec->next_generation_date->addDays(14),
                'sent_at' => now(),
            ]);

            foreach ($rec->items as $item) {
                InvoiceItem::create([
                    'invoice_id' => $invoice->id,
                    'description' => $item->description,
                    'quantity' => $item->quantity,
                    'unit_price' => $item->unit_price,
                    'total' => $item->total,
                ]);
            }

            // Calculate next generation date
            $nextDate = $rec->next_generation_date->copy();
            switch ($rec->frequency) {
                case 'daily':
                    $nextDate = $nextDate->addDay();
                    break;
                case 'weekly':
                    $nextDate = $nextDate->addWeek();
                    break;
                case 'monthly':
                    $nextDate = $nextDate->addMonth();
                    break;
                case 'yearly':
                    $nextDate = $nextDate->addYear();
                    break;
                default:
                    $nextDate = $nextDate->addMonth();
            }

            $rec->update([
                'last_generated_at' => $rec->next_generation_date,
                'next_generation_date' => $nextDate,
            ]);

            $this->info("Generated Invoice {$invoiceNumber} for Client ID {$rec->client_id}");
        }
    }
}
